#读写切换方式为“hint”时，环境为replication组
# 10051 10052 10053
pid_file "/tmp/fbasecman.pid"
daemonize yes

unix_socket_dir "/tmp"
unix_socket_mode "0644"

log_format "%p %t %l [%i %s] (%c) %m\n"

log_to_stdout no

log_syslog no
log_syslog_ident "odyssey"
log_syslog_facility "daemon"

log_debug yes
log_config yes
log_session yes
log_query yes
log_stats yes
stats_interval 60
promhttp_server_port 1
log_general_stats_prom yes
log_route_stats_prom no
heartbeat_request "select 10086"
enable_guc_sync yes

workers "auto"
resolvers 1

readahead 8192

cache_coroutine 0

coroutine_stack_size 16

nodelay yes

keepalive 15
keepalive_keep_interval 75
keepalive_probes 9
keepalive_usr_timeout 0
locks_dir "/tmp/odyssey"
graceful_die_on_errors yes
enable_online_restart no
bindwith_reuseport yes

host "*"
ports "1"
backlog 128
compression yes

group "postgres" {
	group_mode "replication"
    storage_db "postgres"
    backend_clusters "rep_cluster"
    check "auto"
}

datasources "pg_220" {
	host "127.0.0.1"
	port 1
	cluster_name "rep_cluster"
	weight 10
    tls "disable"
}

datasources "pg_230" {
	host "127.0.0.1"
	port 2
	cluster_name "rep_cluster"
	application_name "pg_240"
	weight 10
    tls "disable"
}

datasources "pg_240" {
	host "127.0.0.1"
	port 3
	cluster_name "rep_cluster"
	application_name "pg_241"
	weight 10
    tls "disable"
}

user "postgres" {
    group_names  "postgres"
    rw_split_method "hint"
    authentication "none"
	storage_user "postgres"

    pool "transaction"
    pool_size 100
	pool "transaction"
	log_debug yes
	pool_discard no
	pool_reserve_prepared_statement yes
	pool_ttl 1
    server_lifetime 3600
    quantiles "0.99,0.95,0.5"
    client_max 1007
}

user "admin" {
    authentication "none"
    pool "session"
    role "admin"
}

log_file "/home/postgres/fly_dev/fbasecman_dev_autotest/test/fbasecman/test_logs/extend_query/rep_hint_pool.log"
log_min_messages "info"
license_dir "/home/postgres/lic"
