"""Global-cache case manifest and consolidation metadata."""

from suites.global_cache.case import GlobalCacheCase

GLOBAL_PS_LIMIT_KEY = "global_prepared_statements_limit"
BACKEND_PS_LIMIT_KEY = "backend_prepared_statements_limit"

GLOBAL_CACHE_CASES = [
    GlobalCacheCase(
        name="reuse_single_and_cross_client",
        summary="在同一用例中验证单连接重复执行与跨客户端 global entry 复用",
        batch=1,
        priority="p0",
        driver="jdbc",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        jdbc={"version": "42.7.7", "prepare_threshold": 1},
        report_level="advanced",
        test_contents=(
            "同一 JDBC 连接首次执行 PreparedStatement 时创建对应 global entry。",
            "同一连接后续执行复用同一条 server prepared statement。",
            "第一个客户端释放后，第二个客户端复用已有 global entry，不创建重复条目。",
        ),
        step_rules=(
            (r"首次 PreparedStatement", "1、2", "检查首次创建和同连接复用"),
            (r"第一个 JDBC 客户端", "3", "检查跨客户端复用和重复条目"),
            (r"JDBC driver 完成.*GC_basic_reuse", "1、2", "确认同连接后续执行完成并返回结果"),
            (r"JDBC driver 完成.*GC_cross_client_reuse", "3", "确认第二客户端执行完成并返回结果"),
        ),
    ),
    GlobalCacheCase(
        name="statement_mapping_lifecycle",
        summary="综合验证 unnamed 覆盖与 named 冲突的 statement 映射生命周期",
        batch=1,
        priority="p0",
        driver="mixed",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        jdbc={"version": "42.7.7", "prepare_threshold": 1},
        report_level="advanced",
    ),
    GlobalCacheCase(
        name="guc_bypass_set_and_reset",
        summary="综合验证 prepared GUC SET report 与 RESET ALL 的 bypass 分类和响应",
        batch=6,
        priority="p0",
        driver="jdbc",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        jdbc={"version": "42.7.7", "prepare_threshold": 1},
        report_level="advanced",
    ),
    GlobalCacheCase(
        name="close_and_disconnect_unref",
        summary="覆盖客户端 Close 和 disconnect unref",
        batch=1,
        priority="p0",
        driver="libpq",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        report_level="advanced",
    ),
    GlobalCacheCase(
        name="capacity_eviction_zero_ref",
        summary="超过全局容量后，只淘汰 ref_count=0 的普通 entry",
        batch=1,
        priority="p0",
        driver="jdbc",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        jdbc={"version": "42.7.7", "prepare_threshold": 1},
        report_level="advanced",
        reload={
            "capacity_limit": 3,
            "seed_count": 3,
            "server_lifetime": 10,
            "wait_timeout": 30,
        },
        notes=["配置 global_prepared_statements_limit=3、server_lifetime=10；先保留 1 条长连接业务 SQL，再建立 3 条短连接业务 SQL，等待它们变成 zero-ref；随后再用 2 次短连接 trigger SQL 逐步施加容量压力，验证被淘汰的只能是 zero-ref 普通条目，长连接条目不能被淘汰。"],
    ),
    GlobalCacheCase(
        name="capacity_mixed_bypass_response_and_zero_ref_shortage",
        summary="混合 bypass-response 保护与 zero-ref 不足：heartbeat/report 保留，discard/普通可淘汰，但最终仍超容量 1 条",
        batch=1,
        priority="p0",
        driver="jdbc",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        jdbc={"version": "42.7.7", "prepare_threshold": 1},
        report_level="advanced",
        reload={
            "capacity_limit": 3,
            "zero_ref_count": 4,
            "server_lifetime": 10,
        },
        assertions={
            "heartbeat_sql": "SELECT 124",
            "guc_report_sql": "SET application_name = 'gc_capacity_fused_report'",
            "discard_all_sql": "DISCARD ALL",
            "pressure_prefix": "gc_capacity_fused_zero_ref",
            "active_trigger_sql": "select name from test where id = ? /* gc_capacity_fused_trigger_active */",
        },
        notes=["融合场景：HEARTBEAT/GUC_SET_REPORT 因 has_bypass_response=1 受保护；DISCARD ALL 虽为 bypass 但无 bypass response，因此与普通 zero-ref 一样可淘汰。若总共需要淘汰 5 条而可淘汰池只有 4 条，最终 total_entries 仍会停在 capacity+1。"],
    ),
    GlobalCacheCase(
        name="ref_count_protects_active_entries",
        summary="active 引用不会因为超容量被删除",
        batch=1,
        priority="p0",
        driver="jdbc",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        jdbc={"version": "42.7.7", "prepare_threshold": 1},
        report_level="advanced",
        reload={
            "capacity_limit": 2,
            "active_count": 4,
        },
        notes=["容量 2 下保持 4 条 active prepared statement 同时存活，验证 ref 保护优先于淘汰。"],
    ),
    GlobalCacheCase(
        name="prepare_before_bind_deploy",
        summary="global hit 但当前 server 未部署时，Bind 前必须补 Parse",
        batch=2,
        priority="p0",
        driver="libpq",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        report_level="advanced",
    ),
    GlobalCacheCase(
        name="bypass_prepare_protocol_sequence",
        summary="heartbeat/GUC bypass 的 P/B/D/E/S 响应顺序",
        batch=2,
        priority="p0",
        driver="libpq",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        report_level="advanced",
        notes=["先复用旧 libpq pipeline 资产纳入正式回归，后续再升级为更细粒度 raw protocol driver。"],
    ),
    GlobalCacheCase(
        name="backend_global_split_eviction",
        summary=(
            "配置 global prepared statement cache 容量上限为 4 条、每个 backend 连接的 "
            "prepared statement cache 容量上限为 2 条；先验证 backend LRU，再验证 "
            "global cache 只淘汰 ref_count=0 的条目"
        ),
        batch=2,
        priority="p1",
        driver="libpq",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        fbasecman={GLOBAL_PS_LIMIT_KEY: 4, BACKEND_PS_LIMIT_KEY: 2},
        report_level="advanced",
        notes=[
            "先在同一事务里连续执行 5 条 prepared SQL，固定打到同一 backend，验证 backend limit=2 下的 LRU Close(S)。",
            "随后断开连接释放引用，再用第 6 条 trigger SQL 触发 global limit=4 下的 zero-ref eviction。",
        ],
    ),
    GlobalCacheCase(
        name="discard_all_clears_backend_cache",
        summary="大写 DISCARD ALL 应清空当前后端 cache，并允许同 SQL 重新 deploy",
        batch=3,
        priority="p1",
        driver="jdbc",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        issue_id="F-001",
        report_level="advanced",
        jdbc={"version": "42.7.7", "prepare_threshold": 1},
        assertions={
            "business_sql": "select name from test where id = ? /* gc_discard_all_redeploy */",
        },
        notes=["固定正向契约：DISCARD ALL 清后端 cache 后，再次执行同 SQL 仍成功，并在 server 侧重新 deploy。"],
    ),
    GlobalCacheCase(
        name="parse_invalid_error_recovery_same_connection",
        summary="首次 Parse/Execute 因表不存在失败后，同连接再次执行同一 PreparedStatement 应恢复成功",
        batch=4,
        priority="p1",
        driver="jdbc",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        report_level="advanced",
        jdbc={"version": "42.7.7", "prepare_threshold": 1},
        notes=["严格复用旧 parse_invalid_error 思路，验证 Parse 失败清理后同连接恢复路径。"],
        evidence={
            "report_log_keywords": (
                "errorresponse", "deleted backend cache", "cleared", "42p01",
                "does not exist",
            ),
        },
        allowed_fbasecman_log_patterns=[
            'error 42p01 relation "test_parse_error" does not exist',
        ],
    ),
    GlobalCacheCase(
        name="shared_global_entry_disconnect_one_client_other_client_reuse_still_ok",
        summary="共享 global entry 时断开一个客户端后，另一个客户端继续复用同一 SQL 仍成功",
        batch=4,
        priority="p0",
        driver="libpq",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        report_level="advanced",
        notes=["在共享 global entry 的基础上继续补一锤：不是只看 ref_count 从 3 到 2，而是要验证剩余客户端还能继续复用同一 SQL 成功执行。"],
    ),
    GlobalCacheCase(
        name="reload_enable_guc_sync_existing_entry",
        summary="已有 GUC PreparedStatement entry 在 reload 打开 enable_guc_sync 后，应按新语义刷新行为而非沿用旧 bypass",
        batch=6,
        priority="p1",
        driver="jdbc",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        report_level="advanced",
        jdbc={
            "version": "42.7.7",
            "prepare_threshold": 1,
            "prefer_query_mode": "extended",
        },
        assertions={
            "start_enable_guc_sync": "no",
            "reload_enable_guc_sync": "yes",
            "guc_name": "extra_float_digits",
            "guc_value": "3",
            "expected_before": "1",
            "expected_after": "3",
        },
        notes=["严格参考老 console/test_reload.sh + test_enable_guc_sync.sql，覆盖已有 GUC entry 在 reload 后的语义刷新。"],
    ),
    GlobalCacheCase(
        name="heartbeat_reload_reclassifies_existing_normal_entry",
        summary="reload 后，已有 SELECT 124 全局缓存条目应从 NORMAL 重分类为 HEARTBEAT，并由缓存直接应答。",
        batch=6,
        priority="p1",
        driver="jdbc",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        jdbc={
            "version": "42.7.7",
            "prepare_threshold": 1,
            "prefer_query_mode": "extended",
        },
        report_level="advanced",
        notes=["严格按新定义流程：初始 heartbeat=123，prepared 执行 124，reload 改 heartbeat=124，再验证 sql_class 从 NORMAL 变 HEARTBEAT。"],
    ),
    GlobalCacheCase(
        name="heartbeat_rule_precedence_over_global",
        summary="同时存在全局 heartbeat 与用户级 heartbeat 时，应优先命中用户级配置",
        batch=6,
        priority="p1",
        driver="jdbc",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        jdbc={
            "version": "42.7.7",
            "prepare_threshold": 1,
            "prefer_query_mode": "extended",
        },
        assertions={
            "global_heartbeat": "select 999",
            "user_heartbeat": "select 124",
            "verify_sql": "SELECT 124",
            "expected_value": "124",
        },
        report_level="advanced",
        notes=["验证 rule/user 级 heartbeat 优先于全局 heartbeat，同一用户发送 SELECT 124 时应返回 124。"],
    ),
    GlobalCacheCase(
        name="same_sql_different_users_isolation",
        summary="不同用户对同一 SQL 但 heartbeat 配置不同，不应出现跨用户 heartbeat 污染",
        batch=10,
        priority="p1",
        driver="jdbc",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        jdbc={
            "version": "42.7.7",
            "prepare_threshold": 1,
            "prefer_query_mode": "extended",
        },
        assertions={
            "shared_sql": "SELECT 124",
            "user1_name": "postgres",
            "user1_heartbeat": "select 124",
            "user2_name": "postgres2",
            "user2_heartbeat": "select 999",
            "expected_user1_value": "124",
            "expected_user2_value": "124",
        },
        report_level="advanced",
        notes=["验证 user1 的 heartbeat/bypass response 不会污染 user2 对同一 SQL 的执行语义。"],
    ),
    GlobalCacheCase(
        name="global_capacity_reload_shrink",
        summary="reload 缩小 global_prepared_statements_limit 后，全局缓存容量与条目数同步收缩",
        batch=3,
        priority="p0",
        driver="jdbc",
        topology="mmr",
        rw_split_method="hint",
        pool_mode="transaction",
        enabled=True,
        jdbc={"version": "42.7.7", "prepare_threshold": 1},
        report_level="advanced",
        reload={
            "before_limit": 10,
            "after_limit": 5,
            "seed_count": 10,
            "server_lifetime": 10,
            "wait_timeout": 30,
        },
        notes=[
            "严格按真实业务流程验证 shrink：先填满 10 条 prepared cache，再等待 ref_count 归零后 reload 缩到 5。",
            "只有 ref_count=0 的 entry 才允许被 shrink 淘汰。"
        ],
    ),
]


NOISE_PATTERNS = [
    "SET extra_float_digits",
    "SET application_name",
    "BEGIN",
    "COMMIT",
]


NEGATIVE_LOG_PATTERNS = [
    "server is null when no bypass",
    "segmentation fault",
    "assertion failed",
    "failed to add outstanding",
    "failed to queue rewritten parse",
    "outstanding_requests.used_list is not empty",
    "server prepared statement cache entry is null",
]


def formal_case_items():
    """Enabled cases included by the default regression gate."""
    return [case for case in GLOBAL_CACHE_CASES if case.enabled]
