from framework.assertions import command_succeeds, rows_equal, sql_fails
from framework.steps import sql_step


TABLE = "fbase_regress_audit_object"
USER = "fbase_regress_audit_user"
RULES = [
    {"owner": "sso", "name": "fbase_regress_sso_stmt", "kind": "stmt"},
    {"owner": "sso", "name": "fbase_regress_sso_object", "kind": "object"},
    {"owner": "sao", "name": "fbase_regress_sao_postgres", "kind": "stmt"},
    {"owner": "sao", "name": "fbase_regress_sao_sso", "kind": "stmt"},
    {"owner": "sao", "name": "fbase_regress_sao_user", "kind": "stmt"},
]


CASE = {
    "id": "mac.audit.rule_setting_permissions",
    "name": "审计规则设置权限与可见性",
    "document": "审计功能转测（邹雪、陈群友）.md",
    "section": "5.2.1-5.2.3",
    "group": "audit",
    "fixtures": [
        "cluster",
        {"type": "settings", "user": "sao", "values": {"fdb.enable_audit": "1"},
         "apply": "reload", "restore_runtime_value": True,
         "purpose": "启用审计规则设置所需的审计开关"},
        {"type": "roles", "create": [{"name": USER, "attributes": "", "login": True}],
         "cleanup_priority": -10},
        {"type": "table", "name": TABLE, "cleanup_priority": 10},
        {"type": "audit_rules", "rules": RULES},
    ],
    "requirements": {"plugins": ["fbase_mac"], "writable_node": True, "node": "primary",
                     "roles": ["sso", "sao"]},
    "prerequisites": [
        "审计功能已开启，fdb_audit 审计规则 UDF 和元数据表存在",
        "普通测试用户和对象级审计所需测试表可用",
    ],
    "steps": [
        sql_step("超级用户不能设置对象级审计规则", "postgres",
                 "SELECT fdb_audit.set_audit_object('fbase_regress_denied_postgres', 'SELECT', 'sao', 'ALL', 'TABLE', 'public', '%s')" % TABLE,
                 "执行失败，仅 SAO/SSO 可以设置审计规则",
                 sql_fails("must be SAO/SSO user can execute this function")),
        sql_step("普通用户不能设置对象级审计规则", USER,
                 "SELECT fdb_audit.set_audit_object('fbase_regress_denied_user', 'SELECT', 'sao', 'ALL', 'TABLE', 'public', '%s')" % TABLE,
                 "执行失败，普通用户无 fdb_audit schema 使用权限，因而不能设置审计规则",
                 sql_fails("permission denied for schema fdb_audit")),
        sql_step("SSO 不能审计普通用户", "sso",
                 "SELECT fdb_audit.set_audit_stmt('fbase_regress_sso_denied_user', 'SELECT', '%s', 'FAIL')" % USER,
                 "执行失败，SSO 只能审计 SAO", sql_fails("SSO can onliy audit sao")),
        sql_step("SSO 不能审计自身", "sso",
                 "SELECT fdb_audit.set_audit_object('fbase_regress_sso_denied_self', 'SELECT', 'sso', 'FAIL', 'TABLE', 'public', '%s')" % TABLE,
                 "执行失败，不能设置审计自身的规则", sql_fails("can not set audit rules for self")),
        sql_step("SSO 设置审计 SAO 的语句级规则", "sso",
                 "SELECT fdb_audit.set_audit_stmt('fbase_regress_sso_stmt', 'SELECT', 'sao', 'FAIL')",
                 "规则创建成功", command_succeeds()),
        sql_step("SSO 设置审计 SAO 的对象级规则", "sso",
                 "SELECT fdb_audit.set_audit_object('fbase_regress_sso_object', 'SELECT', 'sao', 'SUCCESS', 'TABLE', 'public', '%s')" % TABLE,
                 "规则创建成功", command_succeeds()),
        sql_step("SSO 不能直接查看审计规则元数据表", "sso",
                 "SELECT * FROM fdb_audit.audit_rule", "执行失败，权限不足",
                 sql_fails("permission denied")),
        sql_step("SSO 可从审计规则视图查看自身规则", "sso",
                 "SELECT rule_name, rule_type, audit_user, audit_type, user_name, audit_when, obj_type, obj_schema, obj_name "
                 "FROM fdb_audit.audit_rules WHERE rule_name LIKE 'fbase_regress_sso_%' ORDER BY rule_name",
                 "返回 SSO 创建的一条对象级和一条语句级规则",
                 rows_equal([["fbase_regress_sso_object", "OBJECT", "sso", "SELECT", "sao", "SUCCESS", "TABLE", "public", TABLE],
                             ["fbase_regress_sso_stmt", "STMT", "sso", "SELECT", "sao", "FAIL", None, None, None]])),
        sql_step("SAO 不能审计自身", "sao",
                 "SELECT fdb_audit.set_audit_stmt('fbase_regress_sao_denied_self', 'SELECT', 'sao', 'SUCCESS')",
                 "执行失败，不能设置审计自身的规则", sql_fails("can not set audit rules for self")),
        sql_step("SAO 可审计超级用户", "sao",
                 "SELECT fdb_audit.set_audit_stmt('fbase_regress_sao_postgres', 'SELECT', 'postgres', 'SUCCESS')",
                 "规则创建成功", command_succeeds()),
        sql_step("SAO 可审计 SSO", "sao",
                 "SELECT fdb_audit.set_audit_stmt('fbase_regress_sao_sso', 'SELECT', 'sso', 'SUCCESS')",
                 "规则创建成功", command_succeeds()),
        sql_step("SAO 可审计普通用户", "sao",
                 "SELECT fdb_audit.set_audit_stmt('fbase_regress_sao_user', 'UPDATE', '%s', 'SUCCESS')" % USER,
                 "规则创建成功", command_succeeds()),
        sql_step("SAO 可查看 SSO 和 SAO 创建的全部规则", "sao",
                 "SELECT rule_name, audit_user, audit_type, user_name, audit_when FROM fdb_audit.audit_rule "
                 "WHERE rule_name LIKE 'fbase_regress_sso_%' OR rule_name LIKE 'fbase_regress_sao_%' ORDER BY rule_name",
                 "返回两条 SSO 规则和三条 SAO 规则",
                 rows_equal([["fbase_regress_sao_postgres", "sao", "SELECT", "postgres", "SUCCESS"],
                             ["fbase_regress_sao_sso", "sao", "SELECT", "sso", "SUCCESS"],
                             ["fbase_regress_sao_user", "sao", "UPDATE", USER, "SUCCESS"],
                             ["fbase_regress_sso_object", "sso", "SELECT", "sao", "SUCCESS"],
                             ["fbase_regress_sso_stmt", "sso", "SELECT", "sao", "FAIL"]])),
    ],
    "teardown": "audit_rules fixture 按规则所有者删除创建的规则；table 和普通用户 fixture 删除测试对象；settings fixture 恢复审计开关。",
}
