from framework.assertions import command_succeeds, rows_equal
from framework.steps import sql_step, wait_sql_step


TABLE = "fbase_regress_failover_delay"
PUBLICATION = "fbase_regress_delay_pub"
SUBSCRIPTION = "fbase_regress_delay_sub"
SLOT = "fbase_regress_delay_slot"


CASE = {
    "id": "mac.failover_slot.delayed_commit",
    "name": "故障转移逻辑复制槽延迟提交",
    "document": "故障转移槽转测文档.md",
    "section": "3.3.3",
    "group": "failover_slot",
    "fixtures": [
        "cluster",
        {"type": "settings", "node": "primary", "setup": True,
         "restore_runtime_value": True, "apply": "reload",
         "values": {"synchronous_standby_names": "*"},
         "purpose": "为故障转移逻辑槽提供同步备库"},
        {"type": "settings", "node": "primary", "setup": True,
         "restore_runtime_value": True, "apply": "reload",
         "values": {"synchronous_commit": "remote_apply"},
         "purpose": "使专属逻辑 walsender 按备库 apply LSN 等待 failover 槽提交"},
        {"type": "settings", "node": "primary", "user": "sso", "setup": True,
         "restore_runtime_value": True, "apply": "reload",
         "values": {"fdb.password_change_interval": "0"},
         "purpose": "避免密码周期阻断专属逻辑订阅"},
        {"type": "settings", "node": "standby", "setup": True,
         "restore_runtime_value": True, "apply": "reload",
         "values": {"recovery_min_apply_delay": "5s"},
         "purpose": "延后备库重放，以观测 failover 槽在提交点等待同步备库"},
        {"type": "failover_delay_objects", "source_table": TABLE,
         "target_table": TABLE, "publication": PUBLICATION,
         "subscription": SUBSCRIPTION, "slot": SLOT},
    ],
    "requirements": {"writable_node": True, "node": "primary",
                     "groups": ["streaming", "logical"],
                     "nodes": ["standby", "subscriber"]},
    "prerequisites": [
        "主备流复制健康；用例仅建立专属发布、订阅、表和 failover 槽，不使用环境的全表发布订阅",
        "源码 src/backend/replication/logical/decode.c 在 failover_logical 槽提交时等待同步备库确认 LSN",
    ],
    "steps": [
        sql_step("确认物理备库已成为同步备库", "postgres",
                 "SELECT sync_state FROM pg_stat_replication WHERE state = 'streaming'",
                 "返回 sync", rows_equal([["sync"]])),
        sql_step("确认逻辑 walsender 的默认同步模式为 remote_apply", "postgres",
                 "SHOW synchronous_commit", "返回 remote_apply",
                 rows_equal([["remote_apply"]])),
        sql_step("确认备库已配置五秒重放延迟", "postgres",
                 "SHOW recovery_min_apply_delay", "返回 5s", rows_equal([["5s"]]),
                 node="standby"),
        sql_step("在发布端创建专属复制测试表", "postgres",
                 "CREATE TABLE public.%s (id integer PRIMARY KEY, payload text)" % TABLE,
                 "返回 CREATE TABLE", command_succeeds()),
        sql_step("在订阅端创建同结构目标表", "postgres",
                 "CREATE TABLE public.%s (id integer PRIMARY KEY, payload text)" % TABLE,
                 "返回 CREATE TABLE", command_succeeds(), node="subscriber"),
        sql_step("创建仅发布专属表的 publication", "postgres",
                 "CREATE PUBLICATION %s FOR TABLE public.%s" % (PUBLICATION, TABLE),
                 "返回 CREATE PUBLICATION", command_succeeds()),
        sql_step("创建专属 failover 逻辑复制槽", "postgres",
                 "SELECT slot_name FROM pg_create_logical_replication_slot('%s','pgoutput',false,false,true)" % SLOT,
                 "返回专属槽名", rows_equal([[SLOT]])),
        sql_step("确认主库专属槽标记为 failover", "postgres",
                 "SELECT slot_name, failover::text FROM pg_get_replication_slots() WHERE slot_name = '%s'" % SLOT,
                 "返回专属槽名|true", rows_equal([[SLOT, "true"]])),
        wait_sql_step("备库重放后存在同名 failover 槽", "postgres",
                      "SELECT slot_name, failover::text FROM pg_get_replication_slots() WHERE slot_name = '%s'" % SLOT,
                      "返回专属槽名|true", rows_equal([[SLOT, "true"]]),
                      node="standby", timeout=20, interval=1),
        sql_step("订阅端使用专属 failover 槽创建订阅", "postgres",
                 "CREATE SUBSCRIPTION %s CONNECTION 'host=127.0.0.1 port=15432 user=postgres dbname=postgres' PUBLICATION %s WITH (copy_data = false, create_slot = false, slot_name = '%s')" %
                 (SUBSCRIPTION, PUBLICATION, SLOT),
                 "返回 CREATE SUBSCRIPTION", command_succeeds(), node="subscriber"),
        wait_sql_step("专属订阅已连接到 failover 槽", "postgres",
                      "SELECT count(*)::text FROM pg_subscription s JOIN pg_stat_subscription st ON st.subid = s.oid WHERE s.subname = '%s' AND st.relid IS NULL AND st.pid IS NOT NULL" % SUBSCRIPTION,
                      "返回 1", rows_equal([["1"]]), node="subscriber", timeout=20, interval=1),
        sql_step("发布端以 remote_write 提交专属数据", "postgres",
                 "SET synchronous_commit = remote_write; INSERT INTO public.%s VALUES (1, 'delayed-commit')" % TABLE,
                 "返回 SET 和 INSERT 0 1", command_succeeds()),
        sql_step("备库重放延迟期间订阅端尚未收到提交", "postgres",
                 "SELECT count(*)::text FROM public.%s" % TABLE,
                 "返回 0；failover 槽尚未向订阅端发送该提交", rows_equal([["0"]]), node="subscriber"),
        wait_sql_step("同步备库处理提交后订阅端收到数据", "postgres",
                      "SELECT count(*)::text FROM public.%s" % TABLE,
                      "返回 1", rows_equal([["1"]]), node="subscriber", timeout=20, interval=1),
        sql_step("确认同步备库已重放该提交", "postgres",
                 "SELECT count(*)::text FROM public.%s" % TABLE,
                 "返回 1", rows_equal([["1"]]), node="standby"),
    ],
    "teardown": "failover_delay_objects fixture 删除专属订阅、复制槽、发布和两端测试表；settings fixture 恢复同步复制、密码周期和备库重放延迟。",
}
